uses:
  - django
  - celery


pylint:
  disable:
    - django-not-configured
    - import-outside-toplevel
    - unused-import


pyflakes:
  disable:
    - F401


pycodestyle:
  max-line-length: 300


ignore-path:
  - venv


ignore-patterns:
  - .*migrations
  